#!/usr/local/bin/node

var fs = require('fs'),
    sys = require('sys'),
    spawn = require('child_process').spawn,
    exec = require('child_process').exec,
    flag = __dirname + '/.monitor',
    nodeArgs = process.ARGV.splice(2),
    node = null, // removes 'node' and this script
    monitor = null,
    ignoreFilePath = __dirname + '/ignore',
    ignoreFileTime = null,
    ignoreFiles = [flag], // ignore the monitor flag by default
    reIgnoreFiles = null,
    timeout = 1000; // check every 1 second

function startNode() {
  sys.log('[nodemon] starting node');
  node = spawn('node', nodeArgs);
  
  node.stdout.on('data', function (data) {
    sys.print(data);
  });

  node.stderr.on('data', function (data) {
    sys.error(data);
  });

  node.on('exit', function (code, signal) {
    // exit the monitor, but do it gracefully
    if (signal == 'SIGUSR1') {
      // restart
      startNode();
    } else {
      process.exit();
    }
  });
}

function startMonitor() {
  var cmd = 'find . -newer ' + flag + ' -print;';

  exec(cmd, function (error, stdout, stderr) {
    var files = stdout.split(/\n/), finalFiles;

    files.pop(); // remove blank line ending and split
    if (files.length) {
      finalFiles = files.filter(function(file) {
        return !reIgnoreFiles.test(file);
      });

      fs.writeFileSync(flag, '');

      if (finalFiles.length) {
        sys.log('[nodemon] restarting due to changes...');
        finalFiles.forEach(function (file) {
          sys.log('[nodemon] ' + file);
        });
        sys.print('\n\n');
        node.kill('SIGUSR1');        
      }
    }
    
    setTimeout(startMonitor, timeout);
  });
}

require('path').exists(ignoreFilePath, function () {
  var lines, stat = fs.statSync(ignoreFilePath);
  if (!ignoreFileTime || (ignoreFileTime != stat.mtime)) {
    lines = fs.readFileSync(ignoreFilePath).toString().split(/\n/);
    lines.forEach(function (line) {
      // remove comments and trim lines
      line = line.replace(/#.*$/, '').replace(/^(\s|\u00A0)+|(\s|\u00A0)+$/g, '');
      if (line) {
        ignoreFiles.push(line);
      }
    });
    ignoreFileTime = stat.mtime;
    reIgnoreFiles = ignoreFiles.join('|')
  }
});

// touch
fs.writeFileSync(flag, '');

// remove the flag file on exit
process.on('exit', function (code) {
  sys.log('[nodemon] exiting');
  fs.unlink(flag);
});

process.on('uncaughtException', function (err) {
  sys.log('[nodemon] exception in nodemon killing node: ' + err);
  node.kill();
});

sys.log('[nodemon] starting');
startNode();
setTimeout(startMonitor, timeout);